### ISSUE TITLE
Login issues happening again with latest versions

### ISSUE THREAD

**Issue by Thisisaline** [thiagojack/PacketTracer-Fedora#9] opened 2022-08-11 09:34 UTC
Skills for All not launching the browser is happening again with Packet Tracer 8.2 on Fedora 36 even after previous fixes.. Any help would be appreciated.

**Comment by thiagojack** [comment] 2022-08-11 12:06
Hi! I'll be testing this version today and I'll return with news. :)

**Comment by thiagojack** [comment] 2022-08-14 12:16
I tried to reproduce this bug but I haven't success. The Skills 4 All login page opened for me without any extra config. I installed Packet Tracer on a clear Fedora 36 workstation installation.

If you have any other details about your installation, please let me know here.

https://user-images.githubusercontent.com/5920212/184536245-df346fe7-ba12-4e95-9348-22549cf72016.mp4

**Comment by thiagojack** [comment] 2022-08-17 21:54
I'll close this issue because your problem is not about the script. Try to reinstall the Packet Tracer. If you have any log or more information about this problem, please let me know.

**Closed by thiagojack** 2022-08-17 21:54 UTC
Labels: bug
